# nginx Web Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/sstieg/schroedinger-frontend:latest
          # remove imagePullPolicy when stable. Currently we do not take care of version numbers
          imagePullPolicy: Always

          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx

spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leocloud-nginx
  annotations:
    nginx.org/websocket-services: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: it200301.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: appsrv
                port:
                  number: 8080