name: Build Beta Version
on: [push]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'backend/pom.xml' # optional


      - name: compile backend
        working-directory: backend
        run: mvn -B package

      - name: compile frontend
        working-directory: frontend
        run: |
          npm install 
          npm run build
          sudo apt install zip unzip
          zip -r frontend.zip dist/
          ls

      - name: Upload backend to release
        id: upload-backend
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          prerelease: true
          body: "Intermediate Release for Sprint Review"
          file: backend/target/*-runner.jar

      - name: Upload frontend to release
        id: upload-frontend
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          prerelease: true
          body: "Intermediate Release for Sprint Review"
          file: frontend/frontend.zip
      #         tag: ${{ github.ref }}
      #- name: Display url
       # run: |
        #  echo "TODO: tell the server that it should download this url:""
